### ISSUE TITLE
can't not enable with clangd

### ISSUE THREAD

**Issue by lee-shun** [Thiago4532/lsp-semantic.nvim#1]
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp.lua:1018
: not found: "textDocument/semanticTokens/full" request handler for cli
ent "clangd".
stack traceback:
        [C]: in function 'error'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1018: in function 'requ
est'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1485: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_e
ach_buffer_client'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1484: in function 'buf_
request'
        ...pack/packer/start/lsp-semantic.nvim/lua/lsp-semantic.lua:193
: in function 'highlight_buffer'
        ...pack/packer/start/lsp-semantic.nvim/lua/lsp-semantic.lua:199
: in function 'enable_buffer'
        ...er/start/lsp-semantic.nvim/lua/lsp-semantic/commands.lua:21:
 in function 'cmd_enable'
        [string ":lua"]:1: in main chunk

**Comment by Thiago4532** [comment]
What's your clangd version?

**Comment by Thiago4532** [comment]
I haven't documented this plugin yet, sorry about that. You probably didn't setup the plugin, try to add this to your LSP configuration:
```cpp
require'lspconfig'.clangd.setup {
    before_init = require'lsp-semantic.configs'.clangd.before_init
}
```

**Comment by lee-shun** [comment]
➜  ~ clangd --version
clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

**Comment by lee-shun** [comment]
Just tested! Perfect!
Using this plugin finally, I can highlight the member variables! 
![image](https://user-images.githubusercontent.com/46647235/160437771-90bf4cfa-855f-491f-a09a-598b53f750a2.png)

Thank you hero!

**Comment by Thiago4532** [comment]
No problem! :D
The plugin is using the ```CursorHold``` autocmd to update the buffer, you may want to decrease the updatetime to highlight the buffer faster, currently I'm using ```set updatetime=300```.
